### ISSUE TITLE
nnUnet

### ISSUE THREAD

**Issue by Yangchao0053** [282857341/UNet-2022#2]
请问论文里的指标，跟nnUnet的对比，是拿的nnUnet_2d对比的吗？
另外UNet-2022有出3d版的打算吗？为什么是2d版

**Comment by funnyzhou** [comment]
Yes, U-Net-2022 is a 2D segmentation model and is compared against nnUNet-2D in the experiment part. 

The only reason why we do not release the 3D version is that we do not have enough GPUs to run the experiments.

**Comment by Yangchao0053** [comment]
3q
