### ISSUE TITLE
模型跟代码不一致问题

### ISSUE THREAD

**Issue by cxz0101** [282857341/UNet-2022#5]
我看了一下您的代码，我发现你的论文里面写的是DW卷积跟自注意力模块是并行的，但是代码是串行的，可以解释一下嘛？
我看到您的代码的UNet2022.py的中，您是将dw卷积后的结果再输入自注意力层的，可以解释一下嘛，谢谢您了。
感觉这个并行的处理有点看不懂

**Comment by 282857341** [comment]
是这样的，经过normalizetion和torch.roll之后，网络会出现两个分支，两个分支的起始位置分别是：https://github.com/282857341/UNet-2022/blob/71576dfe58fcd61735b6249901c44b6466570484/nnunet/network_architecture/UNet2022.py#L168
和
https://github.com/282857341/UNet-2022/blob/71576dfe58fcd61735b6249901c44b6466570484/nnunet/network_architecture/UNet2022.py#L176
最终在这一段代码会合
https://github.com/282857341/UNet-2022/blob/71576dfe58fcd61735b6249901c44b6466570484/nnunet/network_architecture/UNet2022.py#L181 
第一个分支的结果经过自注意力运算得到x，并在这一段代码和dw会合
https://github.com/282857341/UNet-2022/blob/71576dfe58fcd61735b6249901c44b6466570484/nnunet/network_architecture/UNet2022.py#L115
