### ISSUE TITLE
关于题目的问题

### ISSUE THREAD

**Issue by cxz0101** [282857341/UNet-2022#6]
我对于这个关键词有点不太理解。（Dynamics in Non-isomorphic Architecture）
我说一下我的看法，Non-isomorphic Architecture是同时对feature map做了卷积操作跟SA操作，但是感觉不太像是非同构（异构）这个解释。Dynamics 也就是权重分配的时候是在channel跟spacing维度同时做了attention的操作。不知道我的理解合理嘛，想听一下您的看法，我想组会的时候讲一下您的文章，感觉写的很棒。

**Comment by 282857341** [comment]
这里Non-isomorphic是异构的意思，通俗的解释就是两种不同的结构代指dwconv和self-attention。所以这篇文章我讨论的是权重的动态性在两种不同结构中的表现
